@extends('layouts.main', [
    'pageTitle' => 'Ecommerce Links by Invalley',
    'pageClass' => 'monthly-mix',
    'navItem' => 'services'
])

@section('content')
<div class="wrapper container header floatingOverHeader">
    <div class="col-sm-12 col-lg-5 ml-md-auto text-center px-sm-1 px-md-0 order-lg-12 d-none d-lg-block"></div>
    <div class="col-12 col-md-6" style="float: right;">
            <img class="card-shadow20" src="/img/screens/ecommerce-header.jpg">
   </div>
    <div class="col-sm-12 col-lg-6 px-sm-1 px-md-0 pt-md-3 text-left order-lg-1">
        <h1 class="mb-4 mb-lg-5">Ecommerce Links</h1>

        <p>Want to dominate the front page of Search Engines with a product? Links from social shopping sites can make that happen.</p> 
        <br />
        <p>Let's <strong>drive more traffic to your webshop</strong> and products. Get links from the best social shopping sites.</p>

        <div class="row mt-4 mt-lg-5">
            <div class="col-sm-12 col-md-6 "><a class="btn btn-neutral btn-simple btn-block" href="#explore">Explore </a></div>

            <div class="col-sm-12 col-md-6 "><a class="btn btn-neutral btn-block" href="#order-now">Order now </a></div>
        </div>
    </div>
</div>



<div class="w-divider skew-up">
    <div class="content">
        <a href="#partner" class="btn-continue shadow">
            <i class="fa fa-angle-down fa-2x" aria-hidden="true"></i>
        </a>
    </div>
</div>

<div class="section container bg-neutral">
<div class="row mb-3 mb-md-5 ">
<div class="col-sm-12 text-center">
    <div id="explore"></div>
<h3>Drive More Traffic To Your Webshop</h3>

<p>If you’re trying to increase the number of visitors to your webshop, you should look into Social Shopping sites. Visitors generated by these types of sites typically spend quite a bit of money in your webshop.
<br /><br />
Sites like Kit.com and Fancy.com are fantastic examples. Check out the examples below to see how online stores promote products on these sites (pretty impressive stats!):
</p>
    <br /><br /><br />
    <img class="card-shadow20" src="/img/pic1.png">
    <br /><br /><br />
    <img class="card-shadow20" src="/img/pic2.png">
    <br /><br /><br />
    <p class="text-center" style="font-style: italic;">Brands using social shopping to make <strong>big</strong> profits.</p>

    <br /><br />
    <h3 class="mt-md-5">What Makes Social Shopping Sites So Effective?</h3>
    
    <p><strong>Social shopping is the future when it comes to online shopping</strong> &mdash; In order to reap the benefits, online stores act on this information by sharing their own products on social shopping sites. Most sites will often allow shoppers to add products to wish-, favorite- or gift-lists. Every time this occurs with a particular product, that product will grow in popularity, bringing more attention not only to the product itself, but to the webshop as a whole.
    </p>
    <br />
    <p style="font-style: italic;">"To resolve uncertainty of what to buy, we often look to what others are doing or have done, and take our cue from them. When a product stands out as particularly popular or dominant, we instinctively perceive this as social proof that it is the correct, most valid option." (source: <a href="http://digitalintelligencetoday.com/how-social-commerce-works-the-social-psychology-of-social-shopping/">How Social Commerce Works: The Social Psychology of Social Shopping | Digital Intelligence Today)</a></p>
    <br />
    <p>Even better is the fact that <strong>literally millions of people</strong> visit social shopping sites everyday, searching for products, liking them, and sharing them with friends.</p>
    <br /><br /><br />
    <img class="card-shadow20" src="/img/3facts.png">
    <br /><br /><br />
</div>
</div>
</div>

<div class="w-divider-highlight skew-down">
    <div class="content">
        <a href="#" class="btn-continue">
            <i class="fa fa-angle-down fa-2x" aria-hidden="true"></i>
        </a>
    </div>
</div>

<div class="section bg-highlight">
<div class="container">
    
    <center>
    <div style="text-align:center;">
        <br /><h3>How Does Invalley Help?</h3>
    </div>
    </center>
    <p>Our goal is to increase the visibility of your products, as well as your online store. To do so, we have selected 10 large social shopping sites. Here is a brief outline of what we do for you:
    </p>
    <br /><br />
    <div style="padding-top: 1rem !important; padding-bottom: 1rem !important; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; display: flex;">
        <ul style="padding: 0; max-width: 650px; margin: 0 auto; text-align: left; font-family: 'Source Sans Pro', sans-serif; font-weight: 400; font-size: 1rem; color: #fff; font-size: 1rem; font-weight: 400; display: block;">
            
        <li style="min-height: 2.8125rem; background-size: 2.8125rem; padding-left: 5rem; background-repeat: no-repeat; background-position: 0 0; list-style: none; display: block; margin-bottom: 2rem; background-image: url(../img/icons/check-icon-white_2x.png);">We create <strong>10 professional accounts</strong>, compiled with accurate and detailed information about your webshop. Every account we build contains an avatar, profile description, contact details, and links to any associated social media profiles.</li>
            
        <li style="min-height: 2.8125rem; background-size: 2.8125rem; padding-left: 5rem; background-repeat: no-repeat; background-position: 0 0; list-style: none; display: block; margin-bottom: 2rem; background-image: url(../img/icons/check-icon-white_2x.png);">From there, we add <strong>100 products</strong> (10 per each social shopping site). Just like the profiles, the products are listed with as many details as possible including pricing, a relevant title, photo, and a product description. While the process is quite meticulous, the payoff is well worth the effort.</li> 
            
        <li style="min-height: 2.8125rem; background-size: 2.8125rem; padding-left: 5rem; background-repeat: no-repeat; background-position: 0 0; list-style: none; display: block; margin-bottom: 2rem; background-image: url(../img/icons/check-icon-white_2x.png);">Along with accurate profile and product descriptions, each and every account is optimized for <strong>optimal SEO benefits</strong>. In some cases, you may want to emphasize a specific product or category to potential shoppers. Not a problem! We can easily optimize your accounts for a specific product or category.</li> 

        <li style="min-height: 2.8125rem; background-size: 2.8125rem; padding-left: 5rem; background-repeat: no-repeat; background-position: 0 0; list-style: none; display: block; margin-bottom: 2rem; background-image: url(../img/icons/check-icon-white_2x.png);">All of this takes place within a 14-day period. After 14 days have elapsed, a <strong>complete report</strong> containing all of the new Ecommerce Links is sent to you.</li> 
        </ul>
    </div>
</div>
</div>

<div class="w-divider skew-up">
    <div class="content">
    </div>
</div>


<div class="section container bg-neutral">
<div class="row mb-3 mb-md-5">
<div class="col-sm-12 pb-4 text-center">
<h3 class="mt-md-5">How Does This Benefit Me?</h3>

    <p>As time progresses, you will begin to see that specific products and/or categories will start to rank better. This is because social shopping sites have become highly authoritative.
        <br /><br />
    In the example below, you see how one webshop dominates the entire frontpage with social shopping listings:</p>
    <br /><br />
    <img class="card-shadow20" src="/img/googlesearchpic.png">
    <br /><br /><br /><br />
    <p><strong>Second</strong>, your online store will receive a boost in traffic. It is important to know that most visitors who end up clicking through, will usually have quite a bit of money to spend in your webshop.</p>
    <br /><br /><br />
    <img class="card-shadow20" src="/img/poll.jpg">
    <br /><br /><br />
</div>
</div>
</div>



<div class="w-divider-highlight skew-down ">
    <div class="content">
    </div>
</div>

<div class="section bg-highlight">
<div class="container">
<div class="row align-items-center ">
<div class="col-sm-12 py-5 text-center"><img class="img-fluid mb-4" src="/img/imaging/webcreationuk.png" style="height:55px; width:284.47px" />
<p class="blockquote">I should start with a WOW! These are the type of links I have never used in the past and just got the report today. The websites that I have got the links from are of extremely high quality/authority. One impressing thing – most of the links I have checked are already indexed in Google! It all looks natural. Now the rankings… it seems strange but we just jumped from page 2 to middle of page 1 for a damn competitive keyword while others improved along. <span class="blockquote-footer">Alex, webcreationuk.co.uk</span></p>
</div>
</div>
</div>
</div>



<div class="w-divider skew-down ">
    <div class="content">
        <a href="#partner" class="btn-continue shadow">
            <i class="fa fa-angle-down fa-2x" aria-hidden="true"></i>
        </a>
    </div>
</div>

<div class="section container bg-neutral">
<div class="row mb-3 mb-md-5">
<div class="col-sm-12 pb-4 text-center">
<h3 class="mt-md-5">Monthly Mix: Give Your Site The Beste Chance Of Ranking</h3>
<p class="lead font-weight-normal text-primary text-center mb-5">Incease rankings when you work with Invalley over a longer period of time</p>
    <a href="/services/monthly-mix"><img class="card-shadow20" height="1103px" width="600px" src="/img/mix-ending.png"></a>
</div>
</div>
</div>

<div class="w-divider-highlight skew-down ">
<div class="content">&nbsp;</div>
</div>

<div class="section bg-highlight">
<div class="container">
<div class="row py-3">
<div class="col-sm-12 text-center"><img class="img-fluid mb-4" src="../../img/icons/reseller-icon-ffffff.png" />
<h3 class="mb-3">Important Message For Resellers</h3>

<p class="text-center">If you&rsquo;re reselling our services, you can get discounts of up to 15%! We include your company logo on the reports so your clients will never know who did the hard work. You can easily mark up our packages without having to worry about missed deadlines, broken links, or low quality content.</p>
<br />
<p class="text-center">Being a reliable and professional business partner is something we take very seriously. <a class="text-warning" href="mailto:help@invalley.com">Contact us</a> if you plan on ordering 3 or more <em>packages</em> for your clients.</p>
</div>
</div>
</div>
</div>

<div class="w-divider skew-down ">
<div class="content"><a class="btn-continue shadow" href="#partner"><i class="fa fa-angle-down fa-2x" aria-hidden="true"></i> </a></div>
</div>

<div class="section bg-neutral bg-shadow pt-5 ">

    <div class="container">
        <div class="row py-3">
            <div class="col-sm-12 text-center">
                <h3 class="text-primary text-center mb-5">
                    Order Your Ecommerce Links Package
                </h3>
            </div>
        </div>

 

        <div class="row py-3">

            <div class="col-sm-12 col-md-9 pr-sm-3 pr-md-0">
                <p class="text-left">
                    <span class="text-muted font-italic">
                    "Search Engine Optimization is my full-time job. It's what I do 24/7. It requires non-stop analysis,
                    testing, consistent link building and maintenance in order to stay ahead of your competition. No two
                    websites or niches are the same, so the longer Invalley get to work with you and your business, the more
                    we can do to increase rankings and drive traffic to your websites."
                    </span>
                    <span class="text-primary text-right d-block mt-3">
                    Joost Smedts, Co-Founder Invalley
                </span>
                </p>

            </div>

            <div class="col-sm-12 col-md-3 text-center px-5 px-md-3 px-lg-5">
                <img src="../img/tn/Joost%20Smedts.png" style="width: 144px; height: 144px;">
            </div>
        </div>

        <div id="order-now"></div>
        
        <div class="row pt-5">
            <div class="col-sm-12 bg-gradient-r py-3 text-center">
                <h3 class=" mb-0 ">
                    Our Packages
                </h3>
            </div>
        </div>


    </div>
</div>

<div class="section bg-neutral bg-gradient2 pt-0 mt-0 " style="">
    <div class="container">
        <div class="row pb-3 bg-transparent">
            <div class="col-sm-12 col-md-4 py-1 text-center text-d-block ">
                <div class="bg-white ml-0">
                    <img style="width: 200px; height: 180.44px;" src="/img/icons/monthly-mix-box-icon.png" />

                    <span class="h6 mt-3 mb-1 tracking-500">Monthly Mix</span>
                    <span class="display-4 leading-1">
                        <small class="currency">$</small>299
                    </span>
                    <span class="text-secondary tracking-200">per month</span>
                    <span class="text-secondary px-md-1 px-lg-2 px-xl-4 mt-4">
                        Choose the Monthly Mix Basic package to get a diversified set of <strong>20 backlinks</strong> per month.
                    </span>

                    <ul class="checklist checklist-small ">
                        <li>
                            20 Unique Backlinks Per Month
                        </li>
                        <li>
                            URL And Keyword Analysis
                        </li>
                        <li>
                            17 Bundled Link Strategies
                        </li>
                        <li>
                            5 URLs And Keywords To Target
                        </li>
                        <li>
                            And much more...
                        </li>
                    </ul>
                    <div style="margin-bottom: -120px;"></div>

                        <a href="" class="d-block text-center">
                            <i class="fa fa-angle-down fa-2x" aria-hidden="true"></i>
                        </a>
                    
                    <center><div style="width: 300px;"><button onclick="window.location.href='/services/monthly-mix#order-now'" type="submit" class="btn-neutral2">Discover</button></div></center>
                        <br />
                </div>
            </div>

            <div class="col-sm-12 col-md-4 py-1 text-center  text-d-block ">
                <div class="bg-white ">
                    <img style="width: 200px; height: 180.44px;" src="/img/icons/ecommerce-links-icon.png" />

                    <span class="h6 mt-3 mb-1 tracking-500">Ecommerce Links</span>
                    <span class="display-4 leading-1">
                    <small class="currency">$</small>99
                    </span>
                    <span class="text-secondary tracking-200">one-time</span>
                    <span class="text-secondary px-md-1 px-lg-2 px-xl-4 mt-4">
                        Dominate your niche with the Ecommerce Links package. Get great results with:
                    </span>
                    <ul class="checklist checklist-small">
                        <li>
                            10 Powerful Ecommerce Links
                        </li>
                        <li>
                            Targeting Of Up To 100 Products
                        </li>
                        <li>
                            Targeting Of 10 Product Categories
                        </li>
                        <li>
                            10 Optimized Shopping Accounts
                        </li>
                        <li>
                            Report Within 14 Days
                        </li>
                    </ul>
                    <div style="margin-bottom: -120px;"></div>
                        <a href="" class="d-block text-center">
                            <i class="fa fa-angle-down fa-2x" aria-hidden="true"></i>
                        </a>

                    <center><div style="width: 300px;"><button onclick="window.location.href='https://dashboard.invalley.com/order/GL9KLK'" type="submit" class="btn btn-primary btn-block my-5">Order now</button></div></center>
                        <br />
                </div>
            </div>

            <div class="col-sm-12 col-md-4 py-1 text-center  text-d-block ">
                <div class="bg-white mr-0">
                    <img style="width: 200px; height: 180.44px;" src="/img/icons/custom-icon.png" />

                    <span class="h6 mt-3 mb-1 tracking-500">Custom Package</span>
                    <span class="text-secondary px-md-1 px-lg-2 px-xl-4 mt-4">
                        Discuss a larger package for maximum impact to your site. Price on request. Click on the button below to send us an email.
                    </span>
                        <center><div style="width: 300px;"><button onclick="window.location.href='/contact-us'" type="submit" class="btn-neutral2">Contact us</button></div></center>
                        <br />
                </div>
            </div>
        </div>

    </div>
</div>

@append